services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
