app = 'coquito-production-app'
primary_region = 'ord'

[build]

[deploy]
  release_command = 'pnpm db:migrate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
